version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'templatedb'
      MYSQL_USER: 'api_user'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_ROOT_PASSWORD: 'changeme'
    ports:
      - '3306:3306'
    volumes:
      - ./db/vol:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  db: