USE templatedb;

CREATE TABLE accounts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username NVARCHAR(255) NOT NULL UNIQUE,
  hash NVARCHAR(255) NOT NULL,
  isSuperAdmin BOOLEAN DEFAULT FALSE,
  createdAt DATETIME NOT NULL DEFAULT NOW()
)